# fly.toml file generated for vwkwk on 2022-12-19T13:31:08+07:00

app = "vwkwk"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  ADMIN_TOKEN="createyouradmintoken"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts] # mount persistent volume
  source="data"
  destination="/data"

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
